---

- name: Install FR24 requirements 
  apt: name={{ item }}
  with_items:
  - make
  - cmake 
  - gcc 
  - pkg-config 
  - libusb-1.0-0
  - libusb-1.0-0-dev
  - libc-dev
  tags:
    - fr24

- name: Blacklist bad driver
  copy: src=etc/modprobe.d/dvb-t.conf dest=/etc/modprobe.d/dvb-t.conf
  tags:
    - fr24

- name: Add osmocom key
  action: shell /usr/bin/ssh-keyscan -H git.osmocom.org >> /etc/ssh/ssh_known_hosts
  tags: 
    - fr24

- name: Clone rtl-sdr
  git: repo=git://git.osmocom.org/rtl-sdr.git dest=/root/rtl-sdr
  tags:
    - fr24

- name: Make rtl-sdr
  shell: cd rtl-sdr && mkdir -p build && cd build && cmake ../ -DINSTALL_UDEV_RULES=ON && make && make install && make clean
  tags:
    - fr24

- name: Run ldconfig
  shell: ldconfig
  tags:
    - fr24

- name: Clone dump1090
  git: repo=https://github.com/MalcolmRobb/dump1090.git dest=/root/dump1090
  tags:
    - fr24

- name: Make dump1090
  shell: make chdir=/root/dump1090/
  tags:
    - fr24

- name: Symlink dump1090
  file: src=/root/dump1090/dump1090 dest=/bin/dump1090 state=link
  tags:
    - fr24

- name: Download Flightradar24
  shell: wget {{ fr24_url }} && tar xvzf fr24feed_*_armhf.tgz && mv fr24feed_armhf/fr24feed flightradar24 && chmod +x flightradar24 && mv fr24feed_armhf/timestamper timestamper && rm fr24feed_*_armhf.tgz && rm -r fr24feed_armhf
  tags:
    - fr24

- name: Create Flightradar24 config
  template: src=fr24feed.ini.j2 dest=/etc/fr24feed.ini
  tags:
    - fr24

- name: Create Flightradar24 launch script
  template: src=flightradar24.sh.j2 dest=/root/flightradar24.sh mode=0755
  tags:
    - fr24

- name: Create Flightradar24 rc.local.d script
  copy: src=etc/rc.local.d/fr24 dest=/etc/rc.local.d/90_fr24 mode=0755
  tags:
    - fr24

- name: Set iptables
  copy: src=etc/network/iptables dest=/etc/network/iptables
  tags: 
    - fr24
    - iptables

- name: Set ip6tables
  copy: src=etc/network/ip6tables dest=/etc/network/ip6tables
  tags: 
    - fr24
    - iptables

- name: Set iptables script
  copy: src=etc/network/if-pre-up.d/iptables dest=/etc/network/if-pre-up.d/iptables mode=0777
  tags: 
    - fr24
    - iptables

- name: Apply iptables rules
  action: shell /etc/network/if-pre-up.d/iptables
  tags: 
    - fr24
    - iptables

- name: Install monitoring 
  apt: name={{ item }}
  with_items:
  - vnstat
  - monit
  - munin-node
  tags:
    - fr24

- name: Set monitrc
  copy: src=etc/monit/monitrc dest=/etc/monit/monitrc
  notify: restart monit
  tags: 
    - fr24

- name: Set munin-node.conf
  copy: src=etc/munin/munin-node.conf dest=/etc/munin/munin-node.conf
  notify: restart munin-node
  tags: 
    - fr24

- name: Remove munin plugins
  file: path={{ item }} state=absent
  with_items:
    - /etc/munin/plugins/cpuspeed
    - /etc/munin/plugins/df_inode
    - /etc/munin/plugins/diskstats
    - /etc/munin/plugins/entropy
    - /etc/munin/plugins/forks
    - /etc/munin/plugins/interrupts
    - /etc/munin/plugins/irqstats
    - /etc/munin/plugins/ntp_kernel_err
    - /etc/munin/plugins/ntp_kernel_pll_freq
    - /etc/munin/plugins/ntp_kernel_pll_off
    - /etc/munin/plugins/open_files
    - /etc/munin/plugins/open_inodes
    - /etc/munin/plugins/postfix_mailvolume
    - /etc/munin/plugins/proc_pri
    - /etc/munin/plugins/threads
  notify: restart munin-node
  tags:
    - fr24

- name: Set munin plugins
  file: src={{ item.path }} dest={{ item.dest }} state=link
  with_items:
    - { path: '/usr/share/munin/plugins/if_',         dest: '/etc/munin/plugins/if_tun0' }
    - { path: '/usr/share/munin/plugins/if_',         dest: '/etc/munin/plugins/if_wlan0' }
    - { path: '/usr/share/munin/plugins/if_err_',     dest: '/etc/munin/plugins/if_err_tun0' }
    - { path: '/usr/share/munin/plugins/if_err_',     dest: '/etc/munin/plugins/if_err_wlan0' }
    - { path: '/usr/share/munin/plugins/ping_',       dest: '/etc/munin/plugins/ping_' }
  notify: restart munin-node
  tags:
    - fr24

- name: Set munin ping config
  copy: src=etc/munin/plugin-conf.d/ping_.conf dest=/etc/munin/plugin-conf.d/ping_.conf
  notify: restart munin-node
  tags:
    - fr24

- name: set hostname
  hostname: name={{ radarhostname }}
  tags:
    - fr24

- name: Set reboot_no_internet.sh
  copy: src=usr/local/bin/reboot_no_internet.sh dest=/usr/local/bin/reboot_no_internet.sh mode=0755
  tags: 
    - fr24

- cron: name="reboot_no_internet" minute="15,45" job="/usr/local/bin/reboot_no_internet.sh"
  tags:
    - fr24
