---

- name: Blacklist bad driver
  copy: src=etc/modprobe.d/dvb-t.conf dest=/etc/modprobe.d/dvb-t.conf
  tags:
    - fr24

- name: add apt keys
  apt_key: keyserver=pgp.mit.edu id=40C430F5
  tags:
    - fr24
    - apt

- name: Copy fr24 apt source
  copy: src=etc/apt/fr24.list dest=/etc/apt/sources.list.d/fr24.list
  tags:
    - fr24
    - apt

- name: Create Flightradar24 config
  template: src=fr24feed.ini.j2 dest=/etc/fr24feed.ini
  tags:
    - fr24

- name: Install fr24feed
  apt: name=fr24feed state=latest update_cache=true
  tags: 
    - fr24 
    - apt

- service: 
    name: Restart fr24feed
    state: restarted
    tags: 
      - fr24 

- name: Run ldconfig
  shell: ldconfig
  tags:
    - fr24

- name: Set iptables
  copy: src=etc/network/iptables dest=/etc/network/iptables
  tags: 
    - fr24
    - iptables

- name: Set ip6tables
  copy: src=etc/network/ip6tables dest=/etc/network/ip6tables
  tags: 
    - fr24
    - iptables

- name: Set iptables script
  copy: src=etc/network/if-pre-up.d/iptables dest=/etc/network/if-pre-up.d/iptables mode=0777
  tags: 
    - fr24
    - iptables

- name: Apply iptables rules
  action: shell /etc/network/if-pre-up.d/iptables
  tags: 
    - fr24
    - iptables

- name: Install monitoring 
  apt: name={{ item }}
  with_items:
  - vnstat
  - monit
  - munin-node
  tags:
    - fr24

- name: Set monitrc
  copy: src=etc/monit/monitrc dest=/etc/monit/monitrc
  notify: restart monit
  tags: 
    - fr24

- name: Set munin-node.conf
  copy: src=etc/munin/munin-node.conf dest=/etc/munin/munin-node.conf
  notify: restart munin-node
  tags: 
    - fr24

- name: Remove munin plugins
  file: path={{ item }} state=absent
  with_items:
    - /etc/munin/plugins/cpuspeed
    - /etc/munin/plugins/df_inode
    - /etc/munin/plugins/diskstats
    - /etc/munin/plugins/entropy
    - /etc/munin/plugins/forks
    - /etc/munin/plugins/interrupts
    - /etc/munin/plugins/irqstats
    - /etc/munin/plugins/ntp_kernel_err
    - /etc/munin/plugins/ntp_kernel_pll_freq
    - /etc/munin/plugins/ntp_kernel_pll_off
    - /etc/munin/plugins/open_files
    - /etc/munin/plugins/open_inodes
    - /etc/munin/plugins/postfix_mailvolume
    - /etc/munin/plugins/proc_pri
    - /etc/munin/plugins/threads
  notify: restart munin-node
  tags:
    - fr24

- name: Set munin plugins
  file: src={{ item.path }} dest={{ item.dest }} state=link
  with_items:
    - { path: '/usr/share/munin/plugins/if_',         dest: '/etc/munin/plugins/if_tun0' }
    - { path: '/usr/share/munin/plugins/if_',         dest: '/etc/munin/plugins/if_wlan0' }
    - { path: '/usr/share/munin/plugins/if_err_',     dest: '/etc/munin/plugins/if_err_tun0' }
    - { path: '/usr/share/munin/plugins/if_err_',     dest: '/etc/munin/plugins/if_err_wlan0' }
    - { path: '/usr/share/munin/plugins/ping_',       dest: '/etc/munin/plugins/ping_' }
  notify: restart munin-node
  tags:
    - fr24

- name: Set munin ping config
  copy: src=etc/munin/plugin-conf.d/ping_.conf dest=/etc/munin/plugin-conf.d/ping_.conf
  notify: restart munin-node
  tags:
    - fr24

- name: set hostname
  hostname: name={{ radarhostname }}
  tags:
    - fr24

- name: Set reboot_no_internet.sh
  copy: src=usr/local/bin/reboot_no_internet.sh dest=/usr/local/bin/reboot_no_internet.sh mode=0755
  tags: 
    - fr24

- cron: name="reboot_no_internet" minute="15,45" job="/usr/local/bin/reboot_no_internet.sh"
  tags:
    - fr24
